ARRANGE: ROW
ALIGN: BOTTOM
ORDER:
  - LG Display 0x05EF
  - Sharp Corporation 0x148D
  - Ancor Communications Inc ROG PG27AQ
  - Samsung Electric Company C34J79x
SCALING: TRUE
AUTO_SCALE: TRUE
SCALE:
  - NAME_DESC: LG Display 0x05EF
    SCALE: 2
  - NAME_DESC: Sharp Corporation 0x148D
    SCALE: 2
  - NAME_DESC: XG349C
    SCALE: 1.25
MODE:
  - NAME_DESC: MAG274QRF-QD
    WIDTH: 2560
    HEIGHT: 1440
    HZ: 120
  - NAME_DESC: M28U
    MAX: TRUE
VRR_OFF:
  - MAG274QRF-QD

