ARRANGE: ROW
ALIGN: BOTTOM
ORDER:
  - Sharp Corporation 0x148D
  - Unknown 0x05EF
  - ASUS XG32V
  - Ancor Communications Inc ROG PG27AQ
AUTO_SCALE: TRUE
SCALE:
  - NAME_DESC: ASUS XG32V
    SCALE: 1
  - NAME_DESC: Unknown 0x05EF
    SCALE: 2
