ARRANGE: ROW
ALIGN: BOTTOM
ORDER:
  - Sharp Corporation 0x148D
  - Unknown 0x05EF
  - ASUS XG32V
  - Ancor Communications Inc ROG PG27AQ
SCALING: TRUE
AUTO_SCALE: TRUE
SCALE:
  - NAME_DESC: ASUS XG32V
    SCALE: 1
  - NAME_DESC: LG Display 0x05EF
    SCALE: 2
  - NAME_DESC: MAG274QRF-QD
    SCALE: 1
  - NAME_DESC: M28U
    SCALE: 1.75
  - NAME_DESC: Sharp Corporation 0x148D
    SCALE: 2
  - NAME_DESC: C34J79x
    SCALE: 1
MODE:
  - NAME_DESC: MAG274QRF-QD
    WIDTH: 2560
    HEIGHT: 1440
    HZ: 120
  - NAME_DESC: M28U
    MAX: TRUE
VRR_OFF:
  - MAG274QRF-QD

