# todo: grab missing artwork - fetchart embedart plugins

# strange android bug: a space followed by RIGHT SINGLE QUOTATION MARK U+2019 will cause an escaping glitch when displaying; beet modify it to a regular single quote

# don't muck around with discogs; stick with musicbrainz as beets is very tightly coupled

plugins:
  - zero
  - lyrics

directory: ~/music
library: ~/.config/beets/musiclibrary.db

import:
  copy: yes
  write: yes
  move: no

paths:
  # remove the default Non-Album directory
  singleton: $artist/$title

format_item: $albumartist - $album - $track - $title - $format

# zero doesn't currently affect album cruft; manually remove via
#   beet modify -a albumartist_credit= genre= albumtype= label= asin= catalognum= script= language= country= albumstatus= albumdisambig=
zero:
  update_database: true
  fields:
    - albumartist_credit
    - albumdisambig
    - albumstatus
    - albumtype
    - arranger
    - artist_credit
    - asin
    - catalognum
    - composer
    - composer_sort
    - comments
    - country
    - disctitle
    - encoder
    - genre
    - grouping
    - label
    - language
    - lyricist
    - media
    - script
