plugins: zero lyrics discogs

directory: ~/music
library: ~/.config/beets/musiclibrary.db

import:
  copy: yes
  write: yes
  move: no

paths:
  # remove the default Non-Album directory
  singleton: $artist/$title

format_item: $albumartist - $album - $track - $title

# 2.4 (current default) is not widely understood
id3v23: yes

zero:
  update_database: true
  fields:
    - albumartist_credit
    - albumartist_sort
    - albumdisambig
    - albumstatus
    - albumtype
    - arranger
    - artist_credit
    - artist_sort
    - asin
    - catalognum
    - composer
    - composer_sort
    - country
    - genre
    - grouping
    - label
    - language
    - lyricist
    - media
