# todo: grab missing artwork - fetchart embedart plugins

# strange android bug: a space followed by RIGHT SINGLE QUOTATION MARK U+2019 will cause an escaping glitch when displaying; beet modify it to a regular single quote

plugins:
  - zero
  - lyrics
# only use this if musicbrainz doesn't have the metadata
#  - discogs

directory: ~/music
library: ~/.config/beets/musiclibrary.db

import:
  copy: yes
  write: yes
  move: no

paths:
  # remove the default Non-Album directory
  singleton: $artist/$title

format_item: $albumartist - $album - $track - $title - $format

zero:
  update_database: true
  # be conservative when removing fields
  fields:
    - albumartist_credit
    - albumdisambig
    - albumstatus
    - albumtype
    - arranger
    - artist_credit
    - asin
    - catalognum
    - composer
    - composer_sort
    - country
    - genre
    - grouping
    - label
    - language
    - lyricist
    - media
