plugins: zero lyrics

directory: ~/music
library: ~/.config/beets/musiclibrary.db

import:
        copy: yes
        write: yes
        move: no

paths:
        # remove the default Non-Album directory
        singleton: $artist/$title

format_item: $albumartist - $album - $track - $title

# 2.4 (current default) is not widely understood
id3v23: yes

zero:
        fields: artist_sort artist_credit albumartist_sort albumartist_credit genre lyricist composer composer_sort arranger grouping albumtype label asin catalognum language country albumstatus media albumdisambig
        update_database: true
