# TODO mouse wheel scrolls history but does not enter search mode

import = [
"~/.config/alacritty/appearance.toml",
"~/.config/alacritty/bindings.toml",
]

[env]
TERM = "alacritty-direct"

[window]
decorations = "None"

[cursor]
vi_mode_style = "Block"
