# TODO https://github.com/alacritty/alacritty/issues/4754

import = [
"~/.config/alacritty/appearance.toml",
"~/.config/alacritty/bindings.toml",
]

# [env]
# TERM = "alacritty-direct"

[window]
decorations = "None"

[cursor]
vi_mode_style = "Block"
