# TODO https://github.com/alacritty/alacritty/issues/4754

[general]
import = [
	"~/.config/alacritty/appearance.toml",
	"~/.config/alacritty/bindings.toml",
	"~/.config/alacritty/host.toml",
]

# [env]
# TERM = "alacritty-direct"

[cursor]
vi_mode_style = "Block"
