# easytag can be used for single file edits
#
# - rm -rf ~/music-beets ~/.config/beets/musiclibrary.db ~/.config/beets/state.pickle ; mkdir ~/music-beets ; cd ~/music-beets
# - import, use --noautotag for compilations/various artists
# - twiddle
# - beet write
# - move to ~/.music
#
# import:
#   beet import ~/Downloads/NewAlbum
#
# manually fix fails:
#   beet modify -a album:"Once More ’Round The Sun" album="Once More 'Round The Sun"
#   beet modify album:"Once More 'Round The Sun" title:"Once More ’Round The Sun" track:4 title="Once More 'Round The Sun"
#
# detect art in FLAC:
#   metaflac --list music-beets/Mastodon/Blood\ Mountain/01\ The\ Wolf\ Is\ Loose.flac | grep "type: 6 (PICTURE)"
#
# embed art:
#   beet fetchart Blood Mountain
#   beet embedart Blood Mountain
#
# check for lyrics:
#   beet ls lyrics::'^$'
#
# remove album cruft from db:
#   beet modify -a albumartist_sort= albumartist_credit= genre= albumtype= label= asin= catalognum= script= language= country= albumstatus= albumdisambig=
#
# remove mb cruft:
#   beet modify -a mb_trackid= mb_releasetrackid= mb_albumid= mb_artistid= mb_albumartistid= mb_releasegroupid= acoustid_fingerprint= acoustid_id= mtime= added=
#   beet modify mb_trackid= mb_releasetrackid= mb_albumid= mb_artistid= mb_albumartistid= mb_releasegroupid= acoustid_fingerprint= acoustid_id= mtime= added=
#
# remove comment cruft:
#   beet modify -a comments=
#   beet modify comments=
#
# remove dodgey lyrics:
#   beet modify New Album lyrics=''
#
# manually write lyrics:
#   beet modify Weezer Maladroit track:6 lyrics="$(cat 6.txt)"
#
# hunt down any RIGHT SINGLE QUOTATION MARK U+2019 and just replace them with a single quote; android will glitch on this character with no apparent pattern:
#   beet ls | grep ’
#   beet modify Say It Ain’t So title="Say It Ain't So"
#
# compilations:
#   beet modify albumartist="Various Artists" comp=true


# don't muck around with discogs; stick with musicbrainz as beets is very tightly coupled
#
# musicbrainz notes track lengths, however these are ignored in favour of the actual length of the track


# list everything:
#   beet ls -f '$title - $artist - $artist_sort - $artist_credit - $album - $albumartist - $albumartist_sort - $albumartist_credit - $genre - $composer - $grouping - $year - $month - $day - $original_year - $original_month - $original_day - $track - $tracktotal - $disc - $disctotal - $lyrics - $comments - $bpm - $comp - $albumtype - $label - $asin - $catalognum - $script - $language - $country - $albumstatus - $media - $albumdisambig - $disctitle - $encoder - $length - $bitrate - $format - $channels - $bitdepth - $samplerate - $mb_trackid - $mb_releasetrackid - $mb_albumid - $mb_artistid - $mb_albumartistid - $mb_releasegroupid - $acoustid_fingerprint - $acoustid_id - $mtime - $added - $path'
#
# list pertinent:
#   beet ls -f '$artist - $artist_sort - $artist_credit - $album - $albumartist - $albumartist_sort - $albumartist_credit - $comp - $disc/$disctotal - $track/$tracktotal - $genre - $composer - $grouping - $year/$month/$day - $lyrics - $comments - $bpm - $albumtype - $encoder - $length - $bitrate - $format - $channels - $bitdepth - $samplerate - $title'
#
#   beet ls -f '$album - $albumartist - $albumartist_sort - $albumartist_credit - $comp - $artist - $artist_sort - $artist_credit - $disc/$disctotal - $track/$tracktotal - $genre - $composer - $grouping - $year/$month/$day - $lyrics - $comments - $bpm - $albumtype - $encoder - $length - $bitrate - $format - $channels - $bitdepth - $samplerate - $title'


#
# TODO
# - migrate from lyricwiki to genius, as genius has better lyrics with headings, however currently cannot be scraped if there are web annotations


plugins:
  - zero
  - lyrics
  - fetchart
  - embedart
  - permissions

directory: ~/music-beets
library: ~/.config/beets/musiclibrary.db

import:
  log: /tmp/beet.import.log
  copy: yes
  write: yes
  move: no

paths:
  # remove the default Non-Album directory
  singleton: $artist/$title

format_item: $albumartist - $album - $track - $title - $format

# zero doesn't currently affect album cruft; manually remove via recipe above
zero:
  update_database: true
  fields:
    - albumartist_credit
    - albumdisambig
    - albumstatus
    - albumtype
    - arranger
    - artist_credit
    - asin
    - catalognum
    - composer
    - composer_sort
    - country
    - disctitle
    - encoder
    - genre
    - grouping
    - label
    - language
    - lyricist
    - media
    - script

fetchart:
  auto: no

embedart:
  auto: no
  ifempty: yes
  remove_art_file: yes

lyrics:
  # google has a good hit rate, however the results are of variable quality and differing sources
  # lyricwiki has reasonable results, however refuses to host some lyrics e.g. NOFX Best God In Show
  # musixmatch is rubbish
  # manually fall back to genius, which at time of writing fails when there are web page annotations on the lyrics
  sources:
#    - google
    - lyricwiki
#    - musixmatch
#    - genius

permissions:
  file: 664
  dir: 775
