# cp ~/.config/karabiner/karabiner.json ./karabiner.json
# yq karabiner.json --output-format yaml > karabiner.yaml
#
# yq karabiner.yaml --output-format json --indent 4 > karabiner.json
# rcup
global:
  ask_for_confirmation_before_quitting: true
  check_for_updates_on_startup: true
  show_in_menu_bar: true
  show_profile_name_in_menu_bar: false
  unsafe_ui: false
profiles:
  - complex_modifications:
      parameters:
        basic.simultaneous_threshold_milliseconds: 50
        basic.to_delayed_action_delay_milliseconds: 500
        basic.to_if_alone_timeout_milliseconds: 200
        basic.to_if_held_down_threshold_milliseconds: 0
        mouse_motion_to_scroll.speed: 100
      rules:
        - description: close all
          manipulators:
            - from:
                key_code: delete_or_backspace
                modifiers:
                  mandatory:
                    - command
                    - control
                    - option
                    - shift
              to:
                - key_code: comma
                  modifiers:
                    - command
                    - shift
              type: basic
        - description: lock
          manipulators:
            - from:
                key_code: escape
                modifiers:
                  mandatory:
                    - command
                    - control
                    - option
                    - shift
              to:
                - key_code: x
                  modifiers:
                    - command
                    - control
              type: basic
        - description: close
          manipulators:
            - from:
                key_code: delete_or_backspace
                modifiers:
                  mandatory:
                    - command
                    - control
                    - option
              to:
                - key_code: comma
                  modifiers:
                    - command
              type: basic
    simple_modifications:
      - from:
          key_code: caps_lock
        to:
          - key_code: escape
    virtual_hid_keyboard:
      country_code: 0
      indicate_sticky_modifier_keys_state: true
      mouse_key_xy_scale: 100
