[window]
decorations = "Transparent"
padding = { x = 0, y = 18 }
dynamic_padding = true

[selection]
save_to_clipboard = true

[shell]
program = "/bin/zsh"
args = [ "-l" ]

[font]
offset = { y = 1 }

[[keyboard.bindings]]
key = "L"
mode = "~AppCursor|~AppKeypad|~Alt"
mods = "Command"
chars = "\u000c"

[[keyboard.bindings]]
key = "L"
mode = "~AppCursor|~AppKeypad|~Alt"
mods = "Command"
action = "ClearHistory"
